# Generated by Django 4.1 on 2022-08-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.FileField(max_length=255, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contents",
                "verbose_name_plural": "Contents",
                "db_table": "contents",
            },
        ),
        migrations.CreateModel(
            name="Generated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated",
                    models.FileField(max_length=255, null=True, upload_to="images/"),
                ),
            ],
            options={
                "verbose_name": "Generateds",
                "verbose_name_plural": "Generateds",
                "db_table": "generateds",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.FileField(max_length=255, null=True, upload_to="images/"),
                ),
            ],
            options={
                "verbose_name": "Styles",
                "verbose_name_plural": "Styles",
                "db_table": "styles",
            },
        ),
    ]
